### ISSUE TITLE
"diff" command doesn't understand that hyphen means standard input

### ISSUE THREAD

**Issue by seh** [kubernetes-sigs/cli-utils#170]
In #143, we taught _diff_ and its sibling commands to interpret an absent directory argument as implying that it should read from standard input. The `common.processPaths` function [detects this case and synthesizes a single argument: the hyphen](https://github.com/kubernetes-sigs/cli-utils/pull/143/files#diff-cefd10b5b8fa86aa8efda967efafa31dR21-R22). However, _diff_ then fails later when it tries to inspect a file named _-_:

```shell
% echo '
apiVersion: v1
kind: Namespace
metadata:
  name: another
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: something
  namespace: another
data:
  key: value
---
' | cat - inventory-template.yaml | kpt live diff
error: lstat -: no such file or directory
```
Note that error at the end calling _lstat_ on _-_. I think that's happening inside of [`kio.LocalPackageReader.Read`](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/kio/pkgio_reader.go#L183) as it attempts to walk the path _-, called from `common.ExpandPackageDir`.

Note that _kpt live preview_ and _kpt live apply_ seem to work well enough in that same position on the command line.

**Comment by mortent** [comment]
`kpt live preview` and `kpt live apply` use the kubctl builder to read the manifests, while it seems like diff uses the kyaml library. We need to make sure we don't pass the `-` argument to kyaml. I'll take a look at this.

**Comment by seans3** [comment]
Work in progress: https://github.com/kubernetes-sigs/cli-utils/pull/175

**Comment by seans3** [comment]
The `diff` command filters out the inventory object, since these are computed and will always be different than the local inventory ConfigMap template. So, unlike other commands, we need to remove this inventory object from the file list before sending to the `kubectl diff` command underneath. While this is implemented for the directory `DIR` argument, it is not implemented for the new `STDIN` argument (hence the error).
