### ISSUE TITLE
Server-side dry-run support for live preview

### ISSUE THREAD

**Issue by fsommar** [kubernetes-sigs/cli-utils#197]
Hi 👋

We're using `kpt live preview` for PR feedback purposes. We recently ran into a resource-naming issue where the name was not matching the expected Kubernetes regex for metadata.name. This would've been caught earlier if preview supported server-side dry-run.

It'd be great if the server-side dry-run for preview could echo the semantics of `kubectl apply --dry-run=server`.

My guess is that implementing something like this would require 1) update of kubectl dependency and 2) adding a server-side dry-run to preview that delegates to the server-side dry-run strategy in the updated kubectl dependency. Does that sound about right?

I'd be willing to give to give this a try, but I'm not familiar with how to update dependencies (i.e. using `go get` locally adds a ton of new transitive dependencies).

**Comment by seans3** [comment]
Hi @fsommar . Server-side dry-run requires an APIServer version >= 1.16 (it requires server-side apply which is turned on by default in 1.16). Currently, GKE is in the range of 1.14 - 1.16, with 1.17 as the rapid channel. So we're not currently in a position to use server-side apply/dry-run, since some clusters will not understand the server-side apply. Once we can rely on server-side apply, we will change `kpt live apply` and `kpt live preview` to use server-side apply. I'm going to close this issue shortly.

**Comment by seans3** [comment]
...as far as the change needed (once we intend to make it), the import of `kubectl` does not need to change (since it is about 1.18). But we'll need to update the `ApplyOptions` to fill in the server-side flags.

**Comment by fsommar** [comment]
Ok, that makes sense. I saw that there were some server-side-apply-related flags, and figured that maybe at least the server-side dry-run could be exposed as a hidden flag? I created a PR for this in case that'd be an acceptable short-term fix.

**Comment by fsommar** [comment]
I'll close this and then revisit it in the future when GKE is on more recent versions of Kubernetes.

/close
