### ISSUE TITLE
Applier single namespace limitation

### ISSUE THREAD

**Issue by teoyaomiqui** [kubernetes-sigs/cli-utils#208]
I am working on integrating cli-utils with different projects, specifically the applier seems to be very useful. However recently I have hit an issue where we have objects with different namespaces in the same package supplied to applier, and application of resources doesn't even start because of namespace validation here: https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/apply/applier.go#L188-L190

It seems like this limitation has a purpose, however reading the code I couldn't find any reason why that limitation is in place.

Maybe we should reconsider how we use the applier, but before that, It would be really great if I could understand why the limitation is there in a first place, this way we don't go sideways with the architecture and design that is behind cli-utils or misuse the library.

Or maybe the limitation is not need there, any input would be greatly appreciated, thanks in advance.

PS: I am not sure that the `issues` is the correct place to discuss this, so please close it if it's a wrong place, and I will try to reach out some other way, thanks in advance.

**Comment by mortent** [comment]
@teoyaomiqui We are actually working on removing this restriction. It was added earlier to avoid some corner-cases just before the launch of kpt. We have a better understanding of this now, so it is no longer needed.

Once we remove this restriction, there will be no restriction against applying resources into multiple namespaces at the same time. Similarly, it is ok to apply both namespace-scoped and cluster-scoped resources at the same time. 
The only restriction we do need, is that the namespace used for the inventory object can not be part of the set of resources that are being applied. This is because we need to create the inventory before we actually apply any of the resources to make sure we never end up in a situation where we lose track of a resource. Similarly, we need to make sure we never end up pruning the namespace which include the inventory object.

Feel free to file issues here or ask directly in the #kpt channel in kubernetes slack. Most of the ongoing work is being tracked in the [kpt](https://github.com/GoogleContainerTools/kpt) repo.

**Comment by mortent** [comment]
@teoyaomiqui This restriction has been lifted with the change in https://github.com/kubernetes-sigs/cli-utils/pull/212. If you see any situations where it doesn't work as expected, just let us know.
