### ISSUE TITLE
kstatus poller CompletedEvent never sent

### ISSUE THREAD

**Issue by phillebaba** [kubernetes-sigs/cli-utils#232]
In kstatus the poller sends an event type with the event to indicate if an error has occurred or a value has been updated etc.

The following is stated about the event type `CompletedEvent`.
https://github.com/kubernetes-sigs/cli-utils/blob/5a5364921f40d25cbde38367c62f6b1fdda38fc4/pkg/kstatus/polling/event/event.go#L21-L23

As I understand it this means that when all of the resource that are being polled have reached the `CurrentStatus`, the `CompletedEvent` will be sent and the channel is closed. However when my tests with polling a single Deployment has resulted in only receiving `ResourceUpdateEvent` even after the Deployment has reached a ready state.

Is documentation incorrect or have I misunderstood the expected behavior.

**Comment by mortent** [comment]
@phillebaba In a previous version of the kstatus library, we used to have an aggregator inside the poller that would determine when a set of resources had reached the `Current` status. This eventually proved a bit difficult, as we quickly run into issues where we need more flexibility around which resources should reach which status. For example, we might want some resources to be deleted and therefore reach the `NotFound` status rather than `Current`. So we no longer try to determine when to stop polling a set of resources within the polling framework. The status you have found is unfortunately something that remains from the previous version, but should probably be removed.

But we do provide some pieces in the framework that should allow you to compose what you want here. If you look at the status controller in the repo (https://github.com/kubernetes-sigs/cli-utils/blob/master/cmd/status/cmdstatus.go), it uses the collector and aggregator from the polling package to determine when a set of resources have been either all reconciled or all deleted. If you find anything that doesn't work as expected, just file an issue or ping me on the k8s slack (kpt channel).

**Comment by phillebaba** [comment]
Thanks for the info! I understand why this behavior cant be baked into the poller. The use case I am building will not have to deal with the problems you describe, so using the aggregator in the same way as the status controller does will work for me.

Should we remove the `CompletedEvent` or change the docs as to not confuse others who may make the same assumption?
