### ISSUE TITLE
Feature Request: Wait for Jobs to complete

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/cli-utils#350]
We are looking to use this library to understand the status of various k8s objects. I noticed that this library reports status as `Current` when a Job is in progress. 

ref: https://github.com/kubernetes-sigs/cli-utils/blob/a051c61f6730c52cae2ab9a4f8f6529988515b9a/pkg/kstatus/status/core.go#L532-L535

I think this should be reported as `InProgress` so that it is possible to determine when a job is complete.

**Comment by mortent** [comment]
@tamalsaha The reason behind this is described in https://github.com/kubernetes-sigs/cli-utils/issues/329. We do want to make it possible to wait for jobs to complete, but that is not currently supported.

**Comment by karlkfi** [comment]
Maybe rename this: "Feature Request: Wait for Jobs to complete".

The "current" status currently means that the resource matches the spec supplied by the caller and has been reconciled by the controller. The applier is not currently designed to execute and wait for jobs. But we could hypothetically add that.

In the context of Config Sync, which use cli-utils to apply resources from a git repo, it's not super obvious what the desired behavior should be regarding jobs. I suspect the user might even want to specify the waiting behavior on a per-job basis, maybe with an annotation, instead of an applier-wide option.
