### ISSUE TITLE
Feature Request: allow apply to ignore some resources

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/cli-utils#393]
When calling the Applier consecutively in a controller, sometimes we need the Applier to skip ignore some resources in the set. When the resource exists in the cluster, it skips applying for it. When the resource doesn't exist in the cluster, it skips creating it.

@haiyanmeng

**Comment by karlkfi** [comment]
Why skip existing or non-existing resources? That doesn't seem like "apply" to me. Why not just filter out the resources you don't want to apply before passing it to the applier? Or make a wrapper that has the same API but does filtering?

**Comment by haiyanmeng** [comment]
> Why not just filter out the resources you don't want to apply before passing it to the applier?

If the resource has been applied successfully, filtering it out would cause it to be pruned.

> Why skip existing or non-existing resources?

The caller of cli-utils may validate a resource against its schema. 
At time 1, a resource passes the schema validation, and is sent to cli-utils to be applied;
At time 2, the resource config is changed and the resource fails the schema validation. So the caller may want cli-utils to skip the resource. (cli-utils may or may not be able to apply the resource successfully, however, the caller want to delay applying the resource in this case to have better control of the resource status).

**Comment by karlkfi** [comment]
“Skip apply but don’t prune” seems like a potentially valuable use case, but how does the client know the resource hasn’t been modified by another client? There’s no way to know there’s no changes unless you actually do a server-side apply. 

I think your second problem (client side schema validation) could actually be avoiding by switching to package-scoped batch apply instead of namespace-scoped and cluster-scoped batch apply. 

If you have package-scoping you would expect the whole package to fail if any of the resources fail schema validation or hydration. And if you wanted independent lifecycle, you’d make a new separate package. 

-Karl

**Comment by karlkfi** [comment]
I'm adding "invalid" object tracking in https://github.com/kubernetes-sigs/cli-utils/pull/488 which are retained in the inventory if they were previously applied but are now invalid.

We could treat objects with a "skip" annotation the same way.
