### ISSUE TITLE
Bug: apply sets that include both CRD and CR fail when not using a caching RestMapper

### ISSUE THREAD

**Issue by ash2k** [kubernetes-sigs/cli-utils#421]
When the set of applied resources contains a CRD and a CR of that new kind, applier seem to get stuck in a loop, re-trying. I think it's [waiting for the rest mapper to be updated with the new mapping](https://github.com/kubernetes-sigs/cli-utils/blob/231f3f4a699c56fe75aa65b1535b7e9ca3996704/pkg/kstatus/polling/clusterreader/caching_reader.go#L221-L232) from the CRD, but that never happens because nothing invalidates the rest mapper.

I wonder if it's a bug/missing feature or I'm just not using the library correctly?

FYI this is related to https://github.com/kubernetes/kubernetes/issues/64391

**Comment by ash2k** [comment]
I've opened a PR to introduce a proper API for this https://github.com/kubernetes/kubernetes/pull/105623.

**Comment by karlkfi** [comment]
FWIW, I think @justinsb has some code with a lazily populated caching RESTMapper that allows individual schema invalidation, rather than all or nothing rest. It also only grabs a schema as needed, instead of all at once (which currently triggers throttling).

We might want to use something like that instead of the existing CachingRESTClientGetter.
