### ISSUE TITLE
What is the security model of apply-time mutation feature?

### ISSUE THREAD

**Issue by ash2k** [kubernetes-sigs/cli-utils#483]
I was looking at https://github.com/kubernetes-sigs/cli-utils/pull/482 and it ocurred to me - can someone craft an annotation to pull e.g. contents of a `Secret` from another namespace? If there are users of cli-utils that use it in a sensitive context, this feature could create a security issue for them. E.g. cli-utils could be used by a privileged process, that accepts input from users and applies it to the cluster. It may perform some checks to ensure it's ok to apply the resources (e.g. perhaps it validates all namespace fields are set to something valid/restricted). This new feature may be circumventing the restrictions in place.

**Comment by karlkfi** [comment]
This is actually one of the primary reasons we added apply-time-mutation client-side, instead of server-side. Doing it client-side means that it uses the users permissions to read any dependencies.

Of course, if you're using a server-side controller to execute the applier, then you're using the controller's permissions. But that's not much different than the problem the server-side controller already has. 

If you're doing server-side authz based on the resources passed into the applier, you should be fine, because currently the mutator only allows reading from source resources that are in the resource set being applied. However in the future, I want to open that up: https://github.com/kubernetes-sigs/cli-utils/pull/412  If we add support for external dependencies, then any authz you do server-side would need to also read the apply-time-mutation annotations to extract the source references and make sure the user has permission to read from them.

**Comment by karlkfi** [comment]
> can someone craft an annotation to pull e.g. contents of a Secret from another namespace?

Yes. But only if the user/account executing the Applier has permission to read that Secret.

**Comment by karlkfi** [comment]
If that's a problem, we could hypothetically lock it down to same-namespace dependencies later. But I'm not sure what that would imply for cluster-scoped resources, or namespace-scoped resources depending on cluster-scoped resources.
